### ISSUE TITLE
Click 4.0 support

### ISSUE THREAD

**Issue by aviau** [borntyping/python-riemann-client#21]
Hello,

Is there plans for python-click 4.0 support?

python-click 4.0 was packaged in Debian. Therefore, python-riemaann-client's dependency no longer match.

**Comment by borntyping** [comment]
Click 4.0 and 5.0 should be compatible - I can't see any changes to click that would break compatibility. It's just a matter of testing and updating the requirements.

**Comment by borntyping** [comment]
https://github.com/borntyping/python-riemann-client/commit/5e51bfe5cccd651aee5b190266ed3d093d4f55c7
