### ISSUE TITLE
Clarify Query Example

### ISSUE THREAD

**Issue by bearrito** [borntyping/python-riemann-client#25]
I'm am attempting to query my index. I'm fairly sure my syntax is correct. Is there something obviously wrong with my usage?

![query_example](https://cloud.githubusercontent.com/assets/1908139/9837922/295ead94-5a1d-11e5-8164-7b1d5b48b582.png)

**Comment by borntyping** [comment]
This works on my machine - I suggest checking that Riemann is working correctly and is configured to keep the interaction you are sending it. You should be able to list all events in the index with `riemann-client query "true"`.

If you still have problems after this, the versions of `python-riemann-client` and Python itself that you are running would be useful information.

```
$ riemann-client --version
riemann-client, version 6.0.2

$ riemann-client send -s "simple_service" -S "healthy" -m "1.0" --ttl "1000"
{
  "host": "sidestrike", 
  "metric_f": 1.0, 
  "service": "simple_service", 
  "state": "healthy", 
  "ttl": 1000
}

$ riemann-client query 'service = "simple_service"'                         
[
  {
    "host": "sidestrike", 
    "metric_d": 1.0, 
    "metric_f": 1.0, 
    "service": "simple_service", 
    "state": "healthy", 
    "time": 1442229032, 
    "ttl": 1000.0
  }
]
```
