### ISSUE TITLE
Tags being split into individual characters

### ISSUE THREAD

**Issue by alexforrow** [borntyping/python-riemann-client#28]
On version 4.0.0, I'm finding that tags aren't sent correctly. In the following example the 'foo' tag is being received by Riemann as 'f', 'o' and 'o'

`riemann-client send --service test --tag "foo"`

`#riemann.codec.Event{:host "XXX", :service "test", :state nil, :description nil, :metric nil, :tags ["f" "o" "o"], :time 1.455016849106E9, :ttl 60}`

Tested that 3.0.3 works fine.

**Comment by alexforrow** [comment]
Ahh, this is a dupe

**Comment by borntyping** [comment]
I don't seem to be able to recreate this?

**Comment by alexforrow** [comment]
This was a duplicate of #7. Just needed to update.
